name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:

      - name: verify
        run: |
          docker version
          docker compose version
          node -v
          npm -v
          git --version


      - uses: actions/checkout@v5

      - name: Run a multi-line script
        run: ls -l
  job-2:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a multi-line script
        run: ls -l