name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: ls -l
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps: 
      - name: Run a multi-line script
        run: ls -l
  job-3:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a multi-line script
        run: ls -l
  job-4:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a multi-line script
        run: ls -l
  job-5:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a multi-line script
        run: ls -l