name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: mkdir test

      - name: Run a multi-line script
        run: ls -l
  job-2:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a multi-line script
        run: ls -l